identificacion = input("Digite su identificacion: ")
nombres = input("Digite su Nombre: ")
apellido = input("Digite su Apellido: ")
direccion = input("Digite su Direccion: ")
telefono = input("Digite su Telefono: ")
edad = input("Digite su edad: ")
estadoCivil = input("Estado Civil:")
hijos= input("Numero de Hijos:")
estatura = input("Estatura en Centimetros:")
fechaContrato = input("fecha de contratación (Día/mes/año):")
sueldoBasico = input("Sueldo básico:")
diasLabor = input("Días Laborados:")

print("==============================")
print("****DatosRegistrados****")
print("==============================")

print("Identificacion:" + " " + identificacion)
print("Nombres:" + " " + nombres)
print("Apellidos:" + " " + apellido)
print("Drección:" + " " + direccion)
print("Telefono:" + " " + telefono)
print("Edad:" + " " + edad)
print("Estado Civil:" + " " + estadoCivil)
print("Hijos:" + " " + hijos)
print("Estatura:" + " " + estatura)
print("Fecha de Contrato:" + " " + fechaContrato)
print("Sueldo basico:" + " " + sueldoBasico)
print("Dias laborados ed:" + " " + diasLabor)
print("==============================")